# See https://pre-commit.com/ for usage and config
repos:
- repo: local
  hooks:
  - id: black
    name: black
    stages: [commit]
    language: system
    entry: poetry run black
    types: [python]

  - id: flake8
    name: flake8
    stages: [commit]
    language: system
    entry: poetry run flake8
    types: [python]
    exclude: setup.py

  - id: mypy
    name: mypy
    stages: [commit]
    language: system
    entry: poetry run mypy
    types: [python]
    require_serial: true

  - id: pylint
    name: pylint
    language: system
    entry: poetry run pylint
    types: [python]
    args:
      [
        "-rn", # Only display messages
        "-sn", # Don't display the score
        "--rcfile=.pylintrc", # Link to your config file
        "--load-plugins=pylint.extensions.docparams", # Load an extension
      ]